### ISSUE TITLE
Australian + New Zealand moss tree

### ISSUE THREAD

**Issue by nielsklazenga** [bio-org-au/services-g3-retired#2]
This is more a feature request than an issue, but this still seems an appropriate spot to put it.

Doug sent out the link to the test site for the updated ALA taxonomy today. The AusMoss APC tree comes through nicely, but there is a lot of junk coming in through NZOR. 

Doug has said that in the next run AusMoss can own Bryophyta completely. My question is whether, if I enter the relevant NZOR entries into AusMoss, we could produce from NSL, besides the APC tree, a tree that has all Australian and New Zealand taxa.

**Comment by afuchs1** [comment]
This will be possible with the new tree management tool. Doug could then use this tree.

**Comment by nielsklazenga** [comment]
Thanks Anne, that's what I thought.
